### ISSUE TITLE
Assignments for next week

### ISSUE THREAD

**Issue by carvalhocamille** [eangelcortes/boundary_cloaking#1]
- get rid of ; in the .ipynb, and future ones
- investigate pltly and surfaces rendering issues (potential bug report ?)
- make sure your function do not rely on global variables.
- $ pip install line_profiler, or $ conda install line_profiler
- do not compute logterm(n-m) each time in the loop, precompute an array of lorgterm(i) for i in -M:M and then loopup in this array. 
-try to astart some changes, and think about what could be done for the second function
@Carreau

**Comment by carvalhocamille** [comment]
-talk to @Carreau for optimizing the part
    a = np.asmatrix([ν[0][n], ν[1][n]]);
                b = np.asmatrix(rdiff/distance);
                cosθ = np.asscalar(np.matmul(a, b.transpose()));
                cosθ_mn[m, n] = cosθ
-start optimizing the function make_solution_grid the same way

**Comment by carvalhocamille** [comment]
-type notes for the 3 layers
-start a notebook with the ideas we discussed

**Comment by Carreau** [comment]
Let's have a look at the piece of code we want to speed up. 
```
                a = np.asmatrix([ν[0][n], ν[1][n]])
                b = np.asmatrix(rdiff/distance)
                cosθ = np.asscalar(np.matmul(a, b.transpose()));
                cosθ_mn[m, n] = cosθ
```

let's wonder what is what is costly here, into more granularity than lines. 

Let's decompose the critical part in  steps:

```
53  22350   20938.0    0.9    0.9      temp_1 = ν[0][n]
54  22350   19094.0    0.9    0.8      temp_2 = ν[1][n]
55  22350   20798.0    0.9    0.9      temp_3 = [temp_1, temp_2]
56  22350  362512.0   16.2   15.5      a = np.asmatrix(temp_3)
57  22350   66249.0    3.0    2.8      temp_4 = rdiff/distance
58  22350  265984.0   11.9   11.4      b = np.asmatrix(temp_4)
62  22350   61301.0    2.7    2.6      temp_5 = b.transpose()
63  22350  149112.0    6.7    6.4      temp_6 = np.matmul(a, temp_5)
64  22350  113227.0    5.1    4.8      cosθ = np.asscalar(temp_6);
66  22350   24815.0    1.1    1.1      cosθ_mn[m, n] = cosθ
```

You can see that bout 25% of your time is now spent in `asmatrix()`

Now we need to get back to your knowledge of the problem and wonder what are the size of those elements ? And what you are trying to do here. 

As far as I understand you are doing scalar product of vector in a 2D (soon 3D?) space. It may not be worth it at this step to use complicated libraries like numpy for one 2d vector.

Let's try with plain-simple manual multiplication and addition:

```
54  22350  383069.0  17.1  15.7    a = np.asmatrix([ν[0][n], ν[1][n]])
55  22350  322359.0  14.4  13.2    b = np.asmatrix(rdiff/distance)
56                                 
57  22350   31710.0   1.4   1.3    u,v = ν[0][n], ν[1][n]
58  22350   94995.0   4.3   3.9    x,y = b[0,0], b[0,1]
59  22350   28663.0   1.3   1.2    ctheta = u*x+v*y
60                                 
61  22350  287554.0  12.9  11.8    cosθ = np.asscalar(np.matmul(a, b.transpose()));
62                                 
63  22350   24993.0   1.1   1.0    assert ctheta == cosθ
```

We of course make sure the result are the same.

Try to do the same with your calculation of rdiff and distance... is it really worth it (for now) to use numpy arrays in each loop ? 

Once you've done this you'll see that logterm start to take quite a bit of time.

**Comment by carvalhocamille** [comment]
Today's meeting:
-conference stuff done
-cloaking.ipynb, use the optimized function, and run the BIE twice to solve the 2 systems. Maybe add a RHS for the second system.

**Comment by carvalhocamille** [comment]
Today's meeting:
-paper accepted ! travel request pending (stay tuned for booking flights).
-Check signs and formulas, get rid of u_l(BE) on representation in L.
-Solve only a 2x2 system in u_e and dnu_e
-fix issues x_i y_i def (shift by 1/kappa_max, not -2rgrid)
-adjust b_ratio to match visually the layers
-the current works only for circles (due to jacobian)
-check indices in plotting
-try k_l = k_i and k_e different (you should get the same as transmission)
-try 3 different values :)

**Comment by carvalhocamille** [comment]
Today's meeting:
-changed b_ratio to 1/r as discussed
-forgot *dt in interior solution computation
-current test: flipping sign. Seems to work numerically, doesn't make sense mathematically.
-Second attempt: solve BIE (1), then BIE(2) using the computed data

**Comment by carvalhocamille** [comment]
Today's meeting: 
-compare the u_l computed with both methods (using data from BE and data from BI)
-update the intro cell with updated system
-try using the transmission conditions (we know u_l(B_i) we just need to find dvu_l(B_i)). See handwritten notes.

**Comment by carvalhocamille** [comment]
Today's meeting:
-worked on the slides and outline. Meet Friday 11/22 at 10am to practice the talk.
-Cloaking: create a new jupyter notebook to test the new idea (we know u_l(B_i) we just need to find dvu_l(B_i))
-type (in latex) the new idea in the new jupyter noteobook
