### ISSUE TITLE
Ipyvolume 'Video' Error

### ISSUE THREAD

**Issue by eangelcortes** [eangelcortes/boundary_cloaking#2]
From Widget-Plot-Implementation.ipynb

@Carreau
In order to combine ipywidgets with 3D plots, I need to import ipyvolume.  However, I keep getting this issue when I try to import it into the notebook.  This issue has been reported before, but the solutions I found online (mainly updating ipywidgets, pip, conda, ipywebrtc, and reinstalling ipyvolume) do not work.

![image](https://user-images.githubusercontent.com/28453889/65348542-49213080-db96-11e9-9727-be89ccebf76f.png)

I was hoping there was a solution to this issue, since this is the only way to do 3D Plotting with ipywidgets (as far as I've read online so far).

**Comment by Carreau** [comment]
can you try: 
```
import ipywidgets
print(ipywidgets.__version__)
```

Which number do you get ? 
You can also stop by my office – an my computer it works out of the box, so i'm not sure what is happening.

**Comment by eangelcortes** [comment]
I got Version 7.2.1

It does seem like some installation issue on my end.  I'll try to come by your office sometime this week.

**Comment by eangelcortes** [comment]
Actually, it seems like I won't have to come in.  After verifying my version wasn't the latest, I was able to find a way to upgrade ipywidgets (I tried it before, but it seems like it didn't actually upgrade it).  Thanks for your suggestion!
